### ISSUE TITLE
Redundant code 

### ISSUE THREAD

**Issue by Clairvoyant1236** [U-Network/UNetwork#1]
Suggest to delete: 
a) account/account_test.go 
b) cli/LevelDBQuery 
c) cli/consensus 
d) consensus/sbft 
e) consensus/policy.go 
f) consensus/policyLevel.go 
g) net/rpc_test 
h) core/transaction/txAttribute_test.go 

Regression testing needed.

**Comment by yilugit** [comment]
resolved, see https://github.com/U-Network/unetwork/pull/9

**Comment by fl-liu** [comment]
a,b,c,g,h are not resolved yet.

**Comment by AzureBerryWang** [comment]
confirmed , already resolved
