### ISSUE TITLE
RESTfull server cleanup

### ISSUE THREAD

**Issue by doraemon0** [U-Network/UNetwork#16]
RESTfull server support a lots of interfaces, as following:

Api_Getconnectioncount  = "/api/v1/node/connectioncount"
Api_GetblockTxsByHeight = "/api/v1/block/transactions/height/:height"
Api_Getblockbyheight = "/api/v1/block/details/height/:height"
Api_Getblockbyhash = "/api/v1/block/details/hash/:hash"
Api_Getblockheight = "/api/v1/block/height"
Api_Getblockhash = "/api/v1/block/hash/:height"
Api_GetTotalIssued = "/api/v1/totalissued/:assetid"
Api_Gettransaction = "/api/v1/transaction/:hash"
Api_Getasset = "/api/v1/asset/:hash"
Api_GetBalanceByAddr = "/api/v1/asset/balances/:addr"
Api_GetBalancebyAsset = "/api/v1/asset/balance/:addr/:assetid"
Api_GetLockedAsset = "/api/v1/asset/locked/:addr/:assetid"
Api_GetUTXObyAsset = "/api/v1/asset/utxo/:addr/:assetid"
Api_GetUTXObyAddr = "/api/v1/asset/utxos/:addr"
Api_SendRawTx = "/api/v1/transaction"
Api_SendRcdTxByTrans = "/api/v1/custom/transaction/record"
Api_GetStateUpdate = "/api/v1/stateupdate/:namespace/:key"
Api_OauthServerUrl = "/api/v1/config/oauthserver/url"
Api_NoticeServerUrl = "/api/v1/config/noticeserver/url"
Api_NoticeServerState = "/api/v1/config/noticeserver/state"
Api_WebsocketState = "/api/v1/config/websocket/state"
Api_Restart = "/api/v1/restart"
Api_GetContract = "/api/v1/contract/:hash"

Part of them is unuseful for public chain. We should do a cleanup.

**Comment by fmlwlher** [comment]
resolved, see #31
